version: "3.8"

services:
  website:
    build: .
    ports:
      - "80:80"
    environment:
      - 'REACT_APP_FIREBASE_API_KEY:${REACT_APP_FIREBASE_API_KEY}'
      - 'REACT_APP_FIREBASE_APP_ID:${REACT_APP_FIREBASE_APP_ID}'
      - 'REACT_APP_ENVIRONMENT:${REACT_APP_ENVIRONMENT}'
      - 'DEPLOY_SERVICE:${DEPLOY_SERVICE}'